### ISSUE TITLE
Don't need to format twice

### ISSUE THREAD

**Issue by xrobau** [strazto/lsi-sas92xx-m1015-flash-firmware#1]
UEFI machines will boot quite happily from a MSDOS formatted disk. The trick is to just switch from UEFI to BIOS booting, usually in the boot sequence of the machine.

**Comment by strazto** [comment]
Thank you for the comment!
Yes, my UEFI motherboard boots from either, for my machine the difference is in selecting, eg "My Device" rather than "UEFI: My Device Partition 1". 
That being said, megarec only works on the MSDOS BIOS shell, and `sas2flash.efi` only works on the UEFI shell. 

I believe `sas2flsh` MIGHT work on BIOS shell, but I can't confirm that as I never personally used it for my own process.

In the case where you only boot from BIOS, I believe a reboot is still required between step 1 and 2, even if there's no need to reformat the USB.

**Comment by xrobau** [comment]
Sorry, I obviously wasn't clear!

At no point do you need to format your USB drive as GPT.  You only need to format it ONCE, and then put all the relevant files in there.  Here's a link to the stuff you can put on a USB drive, which I've just finished building for a mate.

https://www.dropbox.com/s/7qbedvbbfwb2jvs/LSIUSB.zip?dl=0

Note the efi folder - that's the fallback location for an EFI boot. Most SENSIBLE motherboards have the option 'boot via uefi' or 'boot via bios', but some times you need to manually toggle it.   With that layout, as long as you have that option, that drive will happily boot in UEFI or DOS mode for megarec or sas2flash/sas2hax.

**Comment by strazto** [comment]
> At no point do you need to format your USB drive as GPT. 

Oh, amazing, I now understand that you can boot both the BIOS and EFI version from the MSDOS formatted USB. 

I thought I was a genius for structuring my folder to be bootable either way but it's even better that you don't even need to reformat it twice.

I'll check your dropbox, but I think my directory structure should also be bootable either way.

I might update the readme soon, or if you feel like making a PR that's welcome :)

**Comment by xrobau** [comment]
Yeah, I was just re-reading your readme and realised that you already knew that APART from the 'don't need GPT format' bits.

The only difference with mine is that I have a random selection of other older firmwares to help recover broken ones 8)

**Comment by strazto** [comment]
> Yeah, I was just re-reading your readme and realised that you already knew that APART from the 'don't need GPT format' bits.

Nonetheless, thank you for your contribution! The re-flashing step is actually pretty annoying.

I'll have a look at your shared files and see whether I'd like to add them to this project, I found guides + resources for this procedure pretty fragmented, so it'd be nice to consolidate that, though I also do want to make this project cover the %99 use-case as straightforward as possible so hesitant to add complexity.

**Comment by xrobau** [comment]
Also, the 'need to use UEFI' requirement only occurs if the DOS sas2flash.exe comes up with the `ERROR: Failed to initialize PAL. Exiting program` error. Normally you can just use DOS after the megarec works - it's a BIOS limitation in newer UEFI machines not completely emulating the old BIOS stuff.

**Comment by strazto** [comment]
> Also, the 'need to use UEFI' requirement only occurs if the DOS sas2flash.exe comes up with the `ERROR: Failed to initialize PAL. Exiting program` error.

Although it's handy to know, I think I'd rather not mention that caveat in my  guide, and instead provide the most universal path with the best compatibility (rather than have branching paths for doing the same thing).
